#!/bin/bash

if [ _$4 = _ ];
then

echo "give fileA, fileB, output filename, and an expression to be calculated (using A and B as labels for input files)"
exit

fi


fileA=$1
fileB=$2
outfile=$3
expression=$4
unit=$5

if [ -f $1 ];
then
echo "OK" &> /dev/null
else
echo "file $1 not found"
fi

if [ -f $2 ];
then
echo "OK" &> /dev/null
else
echo "file $2 not found"
fi

rm tmpfileA tmpfileB &> /dev/null

ln -s $fileA tmpfileA
ln -s $fileB tmpfileB

expr=`echo $expression | sed -e "s/A/tmpfileA/g" | sed -e "s/B/tmpfileB/g"`

mathpha clobber=yes ERRMETH="POISS-0" << EOF
$expr
C
$outfile
tmpfileA
%
0
EOF

rm tmpfileA tmpfileB &> /dev/null
