#!/usr/bin/env ruby

#20130509 Takayuki Yuasa
#20130709 Takayuki Yuasa fancybox

#============================================
#
#============================================
cssFileName="style.css"
indexFileName="index.html"
pageTitle="Sample Page"
nPerLine=4
bodyWidth=1100
tableWidth=1000
thumbnailSize=250
thumbnailDir="thumbnails"
largeImageDir="largeImages"

#============================================
# Create thumbnails
#============================================
puts "Creating thumbnails..."
if(!File.exist?(thumbnailDir))then
	`mkdir -p #{thumbnailDir}`
end
if(!File.exist?(largeImageDir))then
	`mkdir -p #{largeImageDir}`
end
for file in ARGV do
	if(!File.exist?(thumbnailDir+"/"+file))then
		puts "Resizing #{file}..."
		`convert -resize #{thumbnailSize}x${thumbnailSize} -auto-orient #{file} #{thumbnailDir}/#{File.basename(file)}`
	end
	if(!File.exist?(largeImageDir+"/"+file))then
		puts "Resizing #{file}..."
		`convert -auto-orient #{file} #{largeImageDir}/#{File.basename(file)}`
	end
end

#============================================
# Javascript
#============================================
if(!File.exist?("js"))then
	`mkdir js`
	`cd js;curl -O http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js; cd ..`
	`cd js;curl -O http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js; cd ..`
	`cd js;curl -O https://codeload.github.com/fancyapps/fancyBox/legacy.zip/v2.1.5;unzip v2.1.5;mv fancyapps-fancyBox* fancybox;cd ..`
end

#============================================
# Create CSS File
#============================================
cssFile=open(cssFileName, "w")

cssFile.write <<EOS
body {
	font-family:'ヒラギノ角ゴ Pro W3','Hiragino Kaku Gothic Pro','メイリオ',Meiryo,'ＭＳ Ｐゴシック',sans-serif;
	font-size: 11pt;
	width: #{bodyWidth}px;
	margin: auto;
	padding-top: 20px;
}

img { 
	border: 1px solid #ccc;
	background-color: #fafafa;
	padding: 5px;
	margin: 10px;
}

table {
	border: none;
	width: #{tableWidth} px;
	font-size: 11pt;
	font-weight: normal;
	text-align: center;
}

tr{
	height: #{thumbnailSize+20}px;
}

td{
	width: #{thumbnailSize+20}px;
}
EOS


#============================================
# Create Index File
#============================================
indexFile=open("#{indexFileName}","w")
indexFile.write <<EOS
<html>
<head>

<script src="js/jquery.min.js"></script>
<script src="js/jquery-ui.min.js"></script> 
<script type="text/javascript" src="js/fancybox/lib/jquery.mousewheel-3.0.6.pack.js"></script>

<!-- Add fancyBox -->
<link rel="stylesheet" href="js/fancybox/source/jquery.fancybox.css?v=2.1.5" type="text/css" media="screen" />
<script type="text/javascript" src="js/fancybox/source/jquery.fancybox.pack.js?v=2.1.5"></script>


<script type="text/javascript">
	$(document).ready(function() {
		$(".fancybox").fancybox({
			prevEffect		: 'none',
			nextEffect		: 'none',
			openEffect		: 'elastic',
			closeEffect		: 'elastic',
			loop					: 'false',
			
			closeBtn		: false
		});
	});
</script>


<title>
#{pageTitle}
</title>
<link rel="stylesheet" type="text/css" href="#{cssFileName}">
<meta charset="UTF-8">
</head>
<body>
<h2>
#{pageTitle}
</h2>
<table>
EOS

i=0
fileIndex=0
for file in ARGV do
	if(i==0)then
		indexFile.write "<tr>\n"
	end
	if(i<nPerLine)then
		date=`jhead #{file}  | grep Date | awk '{print $3,$4}'`
		indexFile.write "<td><a href=\"#{largeImageDir}/#{file}\" rel=\"group\" class=\"fancybox\" title=\"#{date}\"><img src=\"thumbnails/#{file}\"></a><br/>#{date}</td> <!-- fileIndex=#{fileIndex} -->\n"
		if(fileIndex==ARGV.length-1)then
			indexFile.write "</tr>\n"
		end
		i=i+1
		fileIndex=fileIndex+1
	end
	if(i==nPerLine)then
		indexFile.write "</tr>\n"
		i=0
	end
end

indexFile.write <<EOS
</table>
</body>
</html>
EOS
