#!/usr/bin/env ruby

#20130712 Takayuki Yuasa

if(ARGV.length==0)then
 puts "give a file containing mediawiki-formatted text"
 exit
end

for file in ARGV do
 open(file).each(){|line|
  regexp=/\[\[:*Media:(.*?)\]\]/
  while(line=~regexp)do
   puts Regexp.last_match[1].split("|")[0] if Regexp.last_match[1]!=nil
   line.sub!(regexp,"")
  end
  regexp=/\[\[:*File:(.*?)\]\]/
  while(line=~regexp)do
   puts Regexp.last_match[1].split("|")[0] if Regexp.last_match[1]!=nil
   line.sub!(regexp,"")
  end
  regexp=/\[\[:*Image:(.*?)\]\]/
  while(line=~regexp)do
   puts Regexp.last_match[1].split("|")[0] if Regexp.last_match[1]!=nil
   line.sub!(regexp,"")
  end
 }

end
