#!/usr/bin/env ruby

#20100904 Takayuki Yuasa

if(ARGV.length<2)then
STDERR.puts "give a string and a length to which the string should be adjusted"
STDERR.puts "optionally third argument is used as filling character instead of space."
exit
end

str=ARGV[0]
n=ARGV[1].to_i
c=" "
if(ARGV.length==3 and ARGV[2].length==1)then
c=ARGV[2]
end

if(n<=str.length)then
puts str
else
spaces=c*(n-str.length)
puts "#{str}#{spaces}"
end

