#!/usr/bin/env ruby

#2013-10-22 Takayuki Yuasa

# wget --no-host-directories --cut-dirs=5 -A gz -r -np http://darts.isas.jaxa.jp/pub/suzaku/ver2.0/401050050/xis/event_cl/

if(ARGV.length==0)then
	puts "give a download url."
	exit
end

url=ARGV[0]

folderPath=url.split("//")[1].split("/")
folderDepth=folderPath.length-2
if(folderDepth<0)then
	folderDepth=0
end

`wget --no-host-directories --cut-dirs=#{folderDepth} -A gz -r -np #{url}`
