#!/usr/bin/env ruby

#2013-08-30 Takayuki Yuasa

if(ARGV.length==0)then
	puts <<EOS
A wget wrapper that reads a list of urls from a specified file.
Options:
  --hostdir : creates host directory.
  --cut=n   : cuts n directories when saving.
EOS
exit
end

options=[]
specifiedOptions=[]
ARGV.each(){|e|
 if(e.include?("--cut="))then
  options << "-nH --cut-dirs=#{e.gsub("cut=","")}"
  specifiedOptions << e
 end
 if(e.include?("--hostdir"))then
  options << "-x"
  specifiedOptions << e
 end
}

puts options

for e in specifiedOptions do
 ARGV.delete(e)
end

open(ARGV[0]).each(){|e|
	if(e.chomp()!="")then
		`wget #{options.join(" ")} #{e}`
	end
}
