#!/usr/bin/env ruby

#20101104 Takayuki Yuasa

if(ARGV.length==0)then
puts <<EOS
xspec_create_checkplot_xcm_from_a_dataset (data set1 db) (data set2 db) ...

Data set db should contain below :
---from this line---
data     (path to pi file)
backgrnd (path to background file)
response (path to response file)
---to this line---


Example:
---from this line---
data  xis_pi/pis/501053010_xis0.pi
response  xis_pi/rmfs/501053010_xis0.rmf
backgrnd  xis_pi/nxbs/501053010_xis0.pi
---to this line---

EOS
exit
end

i=1
datasets=[]
types=["data","back","resp"]

puts <<EOS
##############################
#This XCM was created by $0
##############################
EOS

ARGV.each{|file|
 h={}
 if(!File.exist?(file))then
  next
 end
 open(file).each{|line|
  a=line.split(" ")
  if(a[0]==nil)then
   next
  end
  types.each{|type|
   if(a[0].include?(type))then
    h[type]=a[1]
   end
  }
 }
 puts "#Data set #{i} was constructed from #{file}"
 if(h.length!=0)then
  datasets.push(h)
  i=i+1
 end
}

puts "#Total #{datasets.length} data sets..."
puts ""

i=1
o=1
datasets.each{|h|
puts <<EOS
#Data Set #{o}
data #{i} #{h["data"]}
response #{i} #{h["resp"]}

data #{i+1} #{h["back"]}
response #{i+1} #{h["resp"]}

data #{i+2} #{h["data"]}
backgrnd #{i+2} #{h["back"]}
response #{i+2} #{h["resp"]}

EOS
i=i+3
o=o+1
}
