#!/usr/bin/env perl

#20070511 Takayuki Yuasa
#20081123 Takayuki Yuasa
#20100124 perl path fixed

#delete multiple space(" ") and print result

if(@ARGV==0){
 print "usage : delete_multiple_space.sh FILE\n";
 exit;
}

open(FILE,"$ARGV[0]");
@file=<FILE>;close FILE;

foreach $line (@file) {
 $line=~s/ +/ /g;
 print $line;
}
  
