#!/usr/bin/env perl

#20070927 Takayuki Yuasa
#20100124 perl path fixed

if(@ARGV==0){
 print "usage : sum_file_rows FILENAME\n";
 exit;
}

open(FILE,"$ARGV[0]");
@file=<FILE>;close FILE;

foreach $line (@file){
 $sum+=$line;
}

print $sum;
