#!/bin/bash

#20090511 Takayuki Yuasa

if [ _$1 = _ ];
then
cat << EOF
usage : mkdircpp (folder name to be created)"
this script creates a folder which contains:
 sources/
 sources/main.cc
 builds/
 Makefile
EOF
fi

dir=$1
mkdir $dir $dir/sources $dir/builds &> /dev/null

cat << EOF > $dir/sources/main.cc
#include <iostream>
#include <string>
#include <math.h>
using namespace std;

int main(int argc,char* argv[]){

}
EOF

cat << EOF > $dir/Makefile
all : builds/main

builds/main : sources/main.cc
	g++ sources/main.cc -o builds/main
EOF
